version: '3.9'

services:
  # MySQL database
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password
    ports:
      - "3306:3306"

  # Redis for Sidekiq
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  # Sidekiq for background jobs
  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379/1
    volumes:
      - ./config/sidekiq_cron.yml:/app/config/sidekiq_cron.yml

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  # Rails web server
  web:
    build:
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    depends_on:
      - db
      - elasticsearch
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql2://root:3017991@db:3306/chat_system_development
      REDIS_URL: redis://redis:6379/0
      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - .:/app
    entrypoint: bash -c "sleep 10 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -b '0.0.0.0'"
